version: "3.0"
services:
  db:
    image: postgres:latest
    container_name: auth_profile_db
    networks:
      - auth_profile
    env_file:
      - .env
    environment:
       POSTGRES_USER: ${DATABASE_USER}
       POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
       POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5438:5432"

networks:
 auth_profile: