version: "3.0"
services:
  db:
    image: postgres:latest
    container_name: auth_profile_db
    networks:
      - referral_app
    env_file:
      - .env
    environment:
       POSTGRES_USER: ${DATABASE_USER}
       POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
       POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5438:5432"

  referral_app:
    container_name: referral_app
    build:
      context: .
    ports:
      - "8002:8002"
    volumes:
      - ./core:/referral_system/core
      - ./profile_api:/referral_system/profile_api
      - ./profile_front:/referral_system/profile_front
    env_file:
      - .env
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8002"
    networks:
      - referral_app
    depends_on:
      - db

networks:
 referral_app: