# Generated by Django 5.0.4 on 2024-04-21 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=12, unique=True, verbose_name='Номер телефона')),
                ('code', models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=4, null=True, verbose_name='Код авторизации')),
                ('shared_invite_code', models.CharField(default=None, max_length=6, null=True, unique=True, verbose_name='Код для приглашения друзей')),
                ('friend_invite_code', models.CharField(default=None, max_length=6, null=True, unique=True, verbose_name='Пригласительный код друга')),
            ],
        ),
    ]
