# Generated by Django 5.0.4 on 2024-04-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api', '0003_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friend_invite_code',
            field=models.CharField(default=None, max_length=6, null=True, verbose_name='Пригласительный код друга'),
        ),
    ]
